# smmargins R marginaleffects reference outputs
# Run with: Rscript generate_r.R
#
# Required R packages:
#   install.packages(c("marginaleffects", "readr", "sandwich"))
#
# `sandwich` is needed for HC0..HC3 / cluster vcovs on `glm` and `lm`;
# without it `marginaleffects` silently falls back to the default cov.

library(marginaleffects)
library(readr)
if (!requireNamespace("sandwich", quietly = TRUE)) {
  stop(
    "Package 'sandwich' is required for HCx / cluster vcovs in ",
    "marginaleffects. Install with: install.packages('sandwich')"
  )
}
library(sandwich)

# Read shared data generated by Python ----------------------------------------
df_a <- read_csv("data/data_seed42.csv", show_col_types = FALSE)
df_b <- read_csv("data/data_seed12345.csv", show_col_types = FALSE)

# Ensure categorical variables are factors
df_a$grp <- factor(df_a$grp)
df_b$grp <- factor(df_b$grp)
df_a$clust <- factor(df_a$clust)

# 1. Logit AME with HC3 -------------------------------------------------------
fit_logit <- glm(y_logit ~ x1 + x2 + grp, data = df_a, family = binomial)
mfx_logit <- avg_slopes(fit_logit, vcov = "HC3")
write_csv(mfx_logit, "r_logit_ame_hc3.csv")

# 2. Poisson AME with HC3 -----------------------------------------------------
fit_pois <- glm(count ~ x1 + x2, data = df_a, family = poisson)
mfx_pois <- avg_slopes(fit_pois, vcov = "HC3")
write_csv(mfx_pois, "r_poisson_ame.csv")

# 3. Simple bootstrap on OLS. Modern marginaleffects exposes resampling
#    via the `inferences()` post-processor rather than a `vcov="bootstrap"`
#    string.
fit_ols <- lm(y_ols ~ x1 + x2, data = df_b)
mfx_ols_boot <- inferences(
  avg_slopes(fit_ols),
  method = "boot",
  R = 1000
)
write_csv(mfx_ols_boot, "r_ols_bootstrap.csv")

# 4. OLS with HC1 -------------------------------------------------------------
fit_ols_poly <- lm(y_ols ~ x1 + I(x1^2) + x2 + x1:x2, data = df_b)
mfx_ols_hc1 <- avg_slopes(fit_ols_poly, vcov = "HC1")
write_csv(mfx_ols_hc1, "r_ols_hc1.csv")

# 5. Logit with cluster VCE ---------------------------------------------------
fit_logit_clust <- glm(y_logit ~ x1 + x2 + grp, data = df_a, family = binomial)
mfx_logit_clust <- avg_slopes(fit_logit_clust, vcov = ~clust)
write_csv(mfx_logit_clust, "r_logit_cluster.csv")

# 6. Logit AME at specific x2 values ------------------------------------------
fit_logit_at <- glm(y_logit ~ x1 + x2 + grp, data = df_a, family = binomial)
# Counterfactual grid: replicate every observation for each x2 level, then
# average slopes by x2 to match smmargins behaviour.
d_long <- data.frame(
  x1 = rep(df_a$x1, each = 3),
  x2 = rep(c(-1, 0, 1), times = nrow(df_a)),
  grp = rep(df_a$grp, each = 3)
)
mfx_logit_at <- avg_slopes(fit_logit_at, variables = "x1", newdata = d_long, by = "x2")
write_csv(mfx_logit_at, "r_logit_at.csv")
