# smmargins R marginaleffects reference outputs
# Run with: Rscript generate_r.R
#
# Required R packages:
#   install.packages(c("marginaleffects", "readr", "sandwich"))
#
# `sandwich` is needed for HC0..HC3 / cluster vcovs on `glm` and `lm`;
# without it `marginaleffects` silently falls back to the default cov.

library(marginaleffects)
library(readr)
if (!requireNamespace("sandwich", quietly = TRUE)) {
  stop(
    "Package 'sandwich' is required for HCx / cluster vcovs in ",
    "marginaleffects. Install with: install.packages('sandwich')"
  )
}
library(sandwich)

# Read shared data generated by Python ----------------------------------------
df_a <- read_csv("data/data_seed42.csv", show_col_types = FALSE)
df_b <- read_csv("data/data_seed12345.csv", show_col_types = FALSE)

# Ensure categorical variables are factors
df_a$grp <- factor(df_a$grp)
df_b$grp <- factor(df_b$grp)
df_a$clust <- factor(df_a$clust)

# 1. Logit AME with HC3 -------------------------------------------------------
fit_logit <- glm(y_logit ~ x1 + x2 + grp, data = df_a, family = binomial)
mfx_logit <- avg_slopes(fit_logit, vcov = "HC3")
write_csv(mfx_logit, "r_logit_ame_hc3.csv")

# 2. Poisson AME with HC3 -----------------------------------------------------
fit_pois <- glm(count ~ x1 + x2, data = df_a, family = poisson)
mfx_pois <- avg_slopes(fit_pois, vcov = "HC3")
write_csv(mfx_pois, "r_poisson_ame.csv")

# 3. Simple bootstrap on OLS. Modern marginaleffects exposes resampling
#    via the `inferences()` post-processor rather than a `vcov="bootstrap"`
#    string.
fit_ols <- lm(y_ols ~ x1 + x2, data = df_b)
mfx_ols_boot <- inferences(
  avg_slopes(fit_ols),
  method = "boot",
  R = 1000
)
write_csv(mfx_ols_boot, "r_ols_bootstrap.csv")

# 4. OLS with HC1 -------------------------------------------------------------
fit_ols_poly <- lm(y_ols ~ x1 + I(x1^2) + x2 + x1:x2, data = df_b)
mfx_ols_hc1 <- avg_slopes(fit_ols_poly, vcov = "HC1")
write_csv(mfx_ols_hc1, "r_ols_hc1.csv")

# 5. Logit with cluster VCE ---------------------------------------------------
fit_logit_clust <- glm(y_logit ~ x1 + x2 + grp, data = df_a, family = binomial)
mfx_logit_clust <- avg_slopes(fit_logit_clust, vcov = ~clust)
write_csv(mfx_logit_clust, "r_logit_cluster.csv")

# 6. Logit AME at specific x2 values ------------------------------------------
fit_logit_at <- glm(y_logit ~ x1 + x2 + grp, data = df_a, family = binomial)
# Counterfactual grid: replicate every observation for each x2 level, then
# average slopes by x2 to match smmargins behaviour.
d_long <- data.frame(
  x1 = rep(df_a$x1, each = 3),
  x2 = rep(c(-1, 0, 1), times = nrow(df_a)),
  grp = rep(df_a$grp, each = 3)
)
mfx_logit_at <- avg_slopes(fit_logit_at, variables = "x1", newdata = d_long, by = "x2")
write_csv(mfx_logit_at, "r_logit_at.csv")

# 0.4 fixtures ===============================================================
# Reuse fit_logit (Logit AME, df_a) from section 1.

# 7. Linear-scale (xb) AME on Logit ------------------------------------------
mfx_linear <- avg_slopes(fit_logit, vcov = "HC3", type = "link")
write_csv(mfx_linear, "r_linear.csv")

# 8. Subgroup AMEs (over=grp) ------------------------------------------------
mfx_over <- avg_slopes(fit_logit, vcov = "HC3", by = "grp")
write_csv(mfx_over, "r_over.csv")

# 9. Weighted AMEs (pweights) ------------------------------------------------
df_a$w <- runif(nrow(df_a), 0.5, 2.0)
fit_logit_w <- glm(y_logit ~ x1 + x2 + grp, data = df_a, family = binomial, weights = df_a$w)
mfx_weighted <- avg_slopes(fit_logit_w, vcov = "HC3")
write_csv(mfx_weighted, "r_weighted.csv")

# 10. Coefficient table for Wald parity --------------------------------------
coef_table <- as.data.frame(summary(fit_logit)$coefficients)
coef_table$term <- rownames(coef_table)
write_csv(coef_table, "r_coef.csv")

# 11. Pairwise comparisons (level vs reference) ------------------------------
# marginaleffects 0.32 doesn't support hypothesis="pairwise" directly; we
# compute level-vs-reference comparisons and let Python build pairwise.
comp_grp <- comparisons(fit_logit, variables = list(grp = "all"))
write_csv(comp_grp, "r_comparisons.csv")

# 0.5 fixtures ===============================================================
# All 0.5 parity fixtures use OLS on df_b so estimates are linear-exact.
fit_ols_b <- lm(y_ols ~ x1 + x2 + dummy, data = df_b)

# 12. values={"x1": "p25"} -- prediction with x1 fixed at its 25th percentile,
#     averaged over the rest of the data.
df_b_p25 <- df_b
df_b_p25$x1 <- as.numeric(quantile(df_b$x1, 0.25))
pred_p25 <- avg_predictions(fit_ols_b, newdata = df_b_p25)
write_csv(pred_p25, "r_values_p25.csv")

# 13. values={"x1": [-1, 0, 1]} -- grid of three predictions, x1 fixed at
#     each value, averaged over the rest.
pred_grid <- avg_predictions(
  fit_ols_b,
  variables = list(x1 = c(-1, 0, 1))
)
write_csv(pred_grid, "r_values_grid.csv")

# 14. newdata= -- average prediction over an out-of-sample frame.
df_holdout <- tail(df_b, 20)
pred_newdata <- avg_predictions(fit_ols_b, newdata = df_holdout)
write_csv(pred_newdata, "r_newdata.csv")

# 15. contrast(a={"dummy":1}, b={"dummy":0}) -- PATE (joint-SE difference).
contrast_dummy <- avg_comparisons(
  fit_ols_b,
  variables = list(dummy = c(0, 1))
)
write_csv(contrast_dummy, "r_contrast_dummy.csv")

# 16. dydx("x1", values={"x2": "p25"}) -- cross-feature: slope wrt x1 with
#     x2 replaced by its 25th percentile.
df_b_x2p25 <- df_b
df_b_x2p25$x2 <- as.numeric(quantile(df_b$x2, 0.25))
slopes_at_p25 <- avg_slopes(
  fit_ols_b,
  variables = "x1",
  newdata = df_b_x2p25
)
write_csv(slopes_at_p25, "r_dydx_at_p25.csv")
