"""Tests against R marginaleffects reference outputs.

Reference outputs are generated by ``generate_r.R``.
These tests are skipped if the reference files are not present.
"""

import pathlib
import numpy as np
import pandas as pd
import pytest
import statsmodels.formula.api as smf
import statsmodels.api as sm
from numpy.testing import assert_allclose

from smmargins import Margins

HERE = pathlib.Path(__file__).parent


def _read_r_csv(path: pathlib.Path):
    return pd.read_csv(path)


def _match_label(ame_labels, r_term):
    """Match an R term (e.g. 'x1') to a smmargins label (e.g. 'dx1').

    smmargins prefixes derivative labels with 'd' (dydx) or 'e' (eyex/eydx).
    We strip the first character when the label otherwise equals the term.
    """
    labels = np.array(ame_labels)
    for prefix in ("d", "e"):
        stripped = np.array([lab[len(prefix):] if lab.startswith(prefix) else lab for lab in labels])
        mask = stripped == r_term
        if np.any(mask):
            return np.where(mask)[0][0]
    return None


# ---------------------------------------------------------------------------
# Shared data fixtures read from CSVs (identical to what R uses)
# ---------------------------------------------------------------------------
@pytest.fixture
def df_seed42():
    return pd.read_csv(HERE / "data" / "data_seed42.csv")


@pytest.fixture
def df_seed12345():
    return pd.read_csv(HERE / "data" / "data_seed12345.csv")


# ---------------------------------------------------------------------------
# 1. Logit AME with HC3
# ---------------------------------------------------------------------------
@pytest.mark.skipif(
    not (HERE / "r_logit_ame_hc3.csv").exists(),
    reason="R reference output not found",
)
def test_logit_ame_hc3_matches_r(df_seed42):
    fit = smf.logit("y_logit ~ x1 + x2 + C(grp)", data=df_seed42).fit(disp=False)
    M = Margins(fit, cov_type="HC3")
    ame = M.dydx(["x1", "x2"])

    ref = _read_r_csv(HERE / "r_logit_ame_hc3.csv")
    for i, row in ref.iterrows():
        if row["term"] in ("grp",):
            # smmargins handles factor contrasts differently; skip
            continue
        idx = _match_label(ame.labels, row["term"])
        assert idx is not None, f"No label match for R term {row['term']} in {ame.labels}"
        assert_allclose(ame.estimate[idx], row["estimate"], atol=1e-6)
        assert_allclose(ame.se[idx], row["std.error"], atol=5e-5)


# ---------------------------------------------------------------------------
# 2. Poisson AME with HC3
# ---------------------------------------------------------------------------
@pytest.mark.skipif(
    not (HERE / "r_poisson_ame.csv").exists(),
    reason="R reference output not found",
)
def test_poisson_ame_matches_r(df_seed42):
    fit = smf.glm("count ~ x1 + x2", data=df_seed42, family=sm.families.Poisson()).fit()
    M = Margins(fit, cov_type="HC3")
    ame = M.dydx(["x1", "x2"])

    ref = _read_r_csv(HERE / "r_poisson_ame.csv")
    for i, row in ref.iterrows():
        idx = _match_label(ame.labels, row["term"])
        assert idx is not None, f"No label match for R term {row['term']} in {ame.labels}"
        assert_allclose(ame.estimate[idx], row["estimate"], atol=1e-6)
        assert_allclose(ame.se[idx], row["std.error"], atol=5e-4)


# ---------------------------------------------------------------------------
# 3. OLS bootstrap
# ---------------------------------------------------------------------------
@pytest.mark.skipif(
    not (HERE / "r_ols_bootstrap.csv").exists(),
    reason="R reference output not found",
)
def test_ols_bootstrap_matches_r(df_seed12345):
    fit = smf.ols("y_ols ~ x1 + x2", data=df_seed12345).fit()
    M = Margins(fit)
    ame = M.dydx(["x1", "x2"], vce="bootstrap", n_boot=1000, boot_seed=42)

    ref = _read_r_csv(HERE / "r_ols_bootstrap.csv")
    for i, row in ref.iterrows():
        idx = _match_label(ame.labels, row["term"])
        assert idx is not None, f"No label match for R term {row['term']} in {ame.labels}"
        assert_allclose(ame.estimate[idx], row["estimate"], atol=1e-10)
        # R inferences() returns percentile CIs but no SE; derive approximate SE
        if "std.error" in row and pd.notna(row["std.error"]):
            r_se = row["std.error"]
        else:
            # Normal approximation: SE = (CI_upper - CI_lower) / (2 * 1.96)
            r_se = (row["conf.high"] - row["conf.low"]) / (2 * 1.96)
        mc_tol = 5 * max(ame.se[idx], r_se) / np.sqrt(1000)
        assert abs(ame.se[idx] - r_se) < mc_tol


# ---------------------------------------------------------------------------
# 4. OLS with HC1 (migrated from Stata reference)
# ---------------------------------------------------------------------------
@pytest.mark.skipif(
    not (HERE / "r_ols_hc1.csv").exists(),
    reason="R reference output not found",
)
def test_ols_hc1_matches_r(df_seed12345):
    fit = smf.ols("y_ols ~ x1 + I(x1**2) + x2 + x1:x2", data=df_seed12345).fit(cov_type="HC1")
    M = Margins(fit)
    ame = M.dydx(["x1", "x2"])

    ref = _read_r_csv(HERE / "r_ols_hc1.csv")
    for i, row in ref.iterrows():
        idx = _match_label(ame.labels, row["term"])
        assert idx is not None, f"No label match for R term {row['term']} in {ame.labels}"
        assert_allclose(ame.estimate[idx], row["estimate"], atol=1e-6)
        assert_allclose(ame.se[idx], row["std.error"], atol=1e-6)


# ---------------------------------------------------------------------------
# 5. Logit with cluster VCE (migrated from Stata reference)
# ---------------------------------------------------------------------------
@pytest.mark.skipif(
    not (HERE / "r_logit_cluster.csv").exists(),
    reason="R reference output not found",
)
def test_logit_cluster_matches_r(df_seed42):
    fit = smf.logit("y_logit ~ x1 + x2 + C(grp)", data=df_seed42).fit(disp=False)
    M = Margins(fit, cov_type="cluster", cov_kwds={"groups": df_seed42["clust"]})
    ame = M.dydx(["x1", "x2"])

    ref = _read_r_csv(HERE / "r_logit_cluster.csv")
    for i, row in ref.iterrows():
        if row["term"] in ("grp",):
            continue
        idx = _match_label(ame.labels, row["term"])
        assert idx is not None, f"No label match for R term {row['term']} in {ame.labels}"
        assert_allclose(ame.estimate[idx], row["estimate"], atol=1e-5)
        assert_allclose(ame.se[idx], row["std.error"], atol=1e-4)


# ---------------------------------------------------------------------------
# 6. Logit AME at specific x2 values (migrated from Stata reference)
# ---------------------------------------------------------------------------
@pytest.mark.skipif(
    not (HERE / "r_logit_at.csv").exists(),
    reason="R reference output not found",
)
def test_logit_at_matches_r(df_seed42):
    fit = smf.logit("y_logit ~ x1 + x2 + C(grp)", data=df_seed42).fit(disp=False)
    M = Margins(fit)
    ame = M.dydx("x1", atexog={"x2": [-1, 0, 1]})

    ref = _read_r_csv(HERE / "r_logit_at.csv")
    for i, row in ref.iterrows():
        # Match by x2 value embedded in the smmargins label.
        # Use a precise suffix match to avoid "1" matching "x2=-1".
        x2_val = row["x2"]
        suffix = f"x2={x2_val}"
        mask = np.array([lab.endswith(suffix) for lab in ame.labels])
        assert np.any(mask), f"No label match for x2={x2_val} in {ame.labels}"
        idx = np.where(mask)[0][0]
        assert_allclose(ame.estimate[idx], row["estimate"], atol=1e-5)
        assert_allclose(ame.se[idx], row["std.error"], atol=1e-4)


# ---------------------------------------------------------------------------
# 0.5 parity: values=, newdata=, contrast
# ---------------------------------------------------------------------------
@pytest.mark.skipif(
    not (HERE / "r_values_p25.csv").exists(),
    reason="R reference output not found",
)
def test_values_p25_matches_r(df_seed12345):
    """values={"x1": "p25"} matches marginaleffects::avg_predictions."""
    fit = smf.ols("y_ols ~ x1 + x2 + dummy", data=df_seed12345).fit()
    M = Margins(fit)
    res = M.predict(values={"x1": "p25"})

    ref = _read_r_csv(HERE / "r_values_p25.csv")
    assert_allclose(res.estimate[0], ref["estimate"].iloc[0], atol=1e-8)
    assert_allclose(res.se[0], ref["std.error"].iloc[0], atol=1e-6)


@pytest.mark.skipif(
    not (HERE / "r_values_grid.csv").exists(),
    reason="R reference output not found",
)
def test_values_grid_matches_r(df_seed12345):
    """values={"x1": [-1, 0, 1]} matches avg_predictions(variables=list(...))."""
    fit = smf.ols("y_ols ~ x1 + x2 + dummy", data=df_seed12345).fit()
    M = Margins(fit)
    res = M.predict(values={"x1": [-1, 0, 1]})

    ref = _read_r_csv(HERE / "r_values_grid.csv").sort_values("x1").reset_index(drop=True)
    for i, row in ref.iterrows():
        assert_allclose(res.estimate[i], row["estimate"], atol=1e-8)
        assert_allclose(res.se[i], row["std.error"], atol=1e-6)


@pytest.mark.skipif(
    not (HERE / "r_newdata.csv").exists(),
    reason="R reference output not found",
)
def test_newdata_matches_r(df_seed12345):
    """newdata= matches avg_predictions(newdata=df_holdout)."""
    fit = smf.ols("y_ols ~ x1 + x2 + dummy", data=df_seed12345).fit()
    M = Margins(fit)
    holdout = df_seed12345.tail(20).reset_index(drop=True)
    res = M.predict(newdata=holdout)

    ref = _read_r_csv(HERE / "r_newdata.csv")
    assert_allclose(res.estimate[0], ref["estimate"].iloc[0], atol=1e-8)
    assert_allclose(res.se[0], ref["std.error"].iloc[0], atol=1e-6)


@pytest.mark.skipif(
    not (HERE / "r_contrast_dummy.csv").exists(),
    reason="R reference output not found",
)
def test_contrast_matches_r(df_seed12345):
    """Margins.contrast diff row matches avg_comparisons (joint SE)."""
    fit = smf.ols("y_ols ~ x1 + x2 + dummy", data=df_seed12345).fit()
    M = Margins(fit)
    joint = M.contrast(a={"dummy": 1}, b={"dummy": 0})

    ref = _read_r_csv(HERE / "r_contrast_dummy.csv")
    # The diff row is labeled "A - B: ...".
    diff_idx = next(i for i, lab in enumerate(joint.labels) if lab.startswith("A - B:"))
    assert_allclose(joint.estimate[diff_idx], ref["estimate"].iloc[0], atol=1e-8)
    assert_allclose(joint.se[diff_idx], ref["std.error"].iloc[0], atol=1e-6)


@pytest.mark.skipif(
    not (HERE / "r_dydx_at_p25.csv").exists(),
    reason="R reference output not found",
)
def test_dydx_with_values_matches_r(df_seed12345):
    """dydx('x1', values={'x2': 'p25'}) matches avg_slopes with x2 replaced."""
    fit = smf.ols("y_ols ~ x1 + x2 + dummy", data=df_seed12345).fit()
    M = Margins(fit)
    ame = M.dydx("x1", values={"x2": "p25"})

    ref = _read_r_csv(HERE / "r_dydx_at_p25.csv")
    assert_allclose(ame.estimate[0], ref["estimate"].iloc[0], atol=1e-8)
    assert_allclose(ame.se[0], ref["std.error"].iloc[0], atol=1e-6)
